# Generated by Django 3.1.2 on 2020-11-12 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Strix', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
    ]
