# Generated by Django 3.1.2 on 2020-11-12 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Strix', '0002_remove_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='approval',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='bspstatus',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='issuedescription',
            field=models.CharField(max_length=1000),
        ),
    ]
