# Generated by Django 3.1.2 on 2020-11-13 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Strix', '0003_auto_20201112_2339'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='bugtype',
            field=models.CharField(blank=True, choices=[('Functional', 'Functional'), ('Performance', 'Performance'), ('Usability', 'Usability'), ('Campatibility', 'Campatibility'), ('Security', 'Security')], max_length=50),
        ),
        migrations.AddField(
            model_name='ticket',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='priority',
            field=models.CharField(blank=True, choices=[('urgent', 'urgent'), ('high', 'high'), ('medium', 'medium'), ('low', 'low')], max_length=50),
        ),
        migrations.AddField(
            model_name='ticket',
            name='severity',
            field=models.CharField(blank=True, choices=[('critical', 'critical'), ('high', 'high'), ('medium', 'medium'), ('low', 'low')], max_length=50),
        ),
    ]
