# Generated by Django 3.1.2 on 2020-11-13 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Strix', '0004_auto_20201113_1353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='video',
        ),
        migrations.AddField(
            model_name='ticket',
            name='file',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='bugtype',
            field=models.CharField(blank=True, choices=[('Functional', 'Functional'), ('Performance', 'Performance'), ('Usability', 'Usability'), ('Compatibility', 'Compatibility'), ('Security', 'Security')], max_length=50),
        ),
    ]
