# Generated by Django 3.1.2 on 2020-11-13 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Strix', '0005_auto_20201113_1508'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='file',
        ),
        migrations.CreateModel(
            name='TicketMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(null=True, upload_to='')),
                ('issuename', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Strix.ticket')),
            ],
        ),
    ]
