# Generated by Django 3.1.2 on 2020-11-13 17:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Strix', '0006_auto_20201113_1634'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticketmedia',
            old_name='file',
            new_name='files',
        ),
        migrations.RemoveField(
            model_name='sprint',
            name='pinned',
        ),
        migrations.CreateModel(
            name='Pinned',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pinned', models.BooleanField(default=False)),
                ('pinnedby', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('sprint', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Strix.sprint')),
            ],
        ),
    ]
