# Generated by Django 3.1.2 on 2020-11-13 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Strix', '0007_auto_20201113_2327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pinned',
            name='pinned',
        ),
    ]
